plugins {
    id 'java'
}

group = 'org.cid'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '0.11.0'
}

test {
    useJUnitPlatform()
}